database:
  name: 'wikidata_claims_refs_parsed.db'

parsing:
  reset_database: True #This is a developer mode to clean-up DB to test soemthing

spacy:
  model: 'en_core_web_sm'

html_fetching:
  batch_size: 10
  delay: 1.0

logging:
  level: 'INFO'
  format: '%(asctime)s - %(levelname)s - %(message)s'

text_processing:
  sentence_slide:
    enabled: true
    window_size: 2  #sliding window for masking sentences
    join_char: ' ' 